"""Regression tests for Telegram HTML generated by the Gmail agent."""

import ast
import logging
import os
import sys
import unittest
from datetime import datetime
from html.parser import HTMLParser
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import AsyncMock, MagicMock, patch


PROJECT_ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from bot.html_utils import escape_html, safe_http_url
from gmail_agent.email_analyzer import JobAnalysis
from gmail_agent.telegram_notifier import format_job_card


def _load_handler_functions(names: list[str], extra_globals: dict | None = None):
    """Load selected handlers without importing optional bot dependencies."""
    handlers_path = PROJECT_ROOT / "bot" / "handlers.py"
    tree = ast.parse(handlers_path.read_text(encoding="utf-8"), filename=str(handlers_path))
    functions = [
        node for node in tree.body
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name in names
    ]
    if len(functions) != len(names):
        found = {function.name for function in functions}
        raise AssertionError(f"Missing handler functions: {set(names) - found}")
    for function in functions:
        function.decorator_list = []
    namespace = {"Message": object, "__file__": str(handlers_path)}
    if extra_globals:
        namespace.update(extra_globals)
    exec(compile(ast.Module(body=functions, type_ignores=[]), str(handlers_path), "exec"), namespace)
    return tuple(namespace[name] for name in names)


def _load_handler_function(name: str, extra_globals: dict | None = None):
    return _load_handler_functions([name], extra_globals)[0]


def _analysis(**overrides) -> JobAnalysis:
    values = {
        "email_id": "gmail-id-1",
        "is_relevant": True,
        "title": "Telegram bot",
        "platform": "Freelancehunt",
        "score": 8.5,
        "reason": "Good fit",
        "budget": "5000 UAH",
        "url": "https://freelancehunt.com/project/1",
        "urgency": "high",
        "why_relevant": "Python automation",
        "red_flags": [],
    }
    values.update(overrides)
    return JobAnalysis(**values)


class _TagCollector(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=False)
        self.tags: list[str] = []
        self.stack: list[str] = []
        self.attributes: list[tuple[str, list[tuple[str, str | None]]]] = []
        self.errors: list[str] = []

    def handle_starttag(self, tag, attrs):
        self.tags.append(tag)
        self.stack.append(tag)
        self.attributes.append((tag, attrs))

    def handle_endtag(self, tag):
        if not self.stack or self.stack[-1] != tag:
            self.errors.append(f"Unbalanced closing tag: {tag}")
            return
        self.stack.pop()


class TestHtmlUtils(unittest.TestCase):
    def test_escape_html_handles_none_and_all_special_characters(self):
        self.assertEqual(escape_html(None), "")
        self.assertEqual(
            escape_html('<tag attr="x">Tom & \'Jerry\'</tag>'),
            "&lt;tag attr=&quot;x&quot;&gt;Tom &amp; &#x27;Jerry&#x27;&lt;/tag&gt;",
        )

    def test_safe_http_url_allows_only_well_formed_http_and_https(self):
        for valid in (
            "http://example.com/job",
            "https://example.com/job?a=1&b=2",
            'https://example.com/job?q="quoted"',
        ):
            with self.subTest(valid=valid):
                self.assertEqual(safe_http_url(valid), valid)

        for invalid in (
            None,
            "",
            "javascript:alert(1)",
            "data:text/html,test",
            "ftp://example.com/file",
            "https:///missing-host",
            "https://example.com:bad/job",
            "https://example.com:99999/job",
            "https://example.com:443:80/job",
            "https://%zz/job",
            "https://example..com/job",
            "https://./job",
            "https://example.com/bad path",
            "https://example.com\\@evil.test",
        ):
            with self.subTest(invalid=invalid):
                self.assertIsNone(safe_http_url(invalid))


class TestJobCardHtml(unittest.TestCase):
    def test_all_dynamic_fields_are_escaped_and_static_markup_remains(self):
        card = format_job_card(_analysis(
            email_id="id<1>&",
            platform="Name & Company",
            title="<script>alert(1)</script>",
            budget="Budget < 5000 & > 100",
            reason="Need <b>Telegram bot</b> & CRM",
            why_relevant="deadline > 2 weeks",
            red_flags=["risk <high>", "A & B"],
        ))

        for raw in ("<script>", "<high>", "<1>", "<b>Telegram bot</b>"):
            self.assertNotIn(raw, card)
        self.assertIn("&lt;script&gt;alert(1)&lt;/script&gt;", card)
        self.assertIn("Name &amp; Company", card)
        self.assertIn("Budget &lt; 5000 &amp; &gt; 100", card)
        self.assertIn("Need &lt;b&gt;Telegram bot&lt;/b&gt; &amp; CRM", card)
        self.assertIn("deadline &gt; 2 weeks", card)
        self.assertIn("risk &lt;high&gt;, A &amp; B", card)
        self.assertIn("<b>New Job Match</b>", card)
        self.assertIn("<code>/reply_job id&lt;1&gt;&amp;</code>", card)
        self.assertIn("<a href=", card)

        parser = _TagCollector()
        parser.feed(card)
        self.assertLessEqual(set(parser.tags), {"a", "b", "code"})
        self.assertEqual(parser.errors, [])
        self.assertEqual(parser.stack, [])
        for tag, attrs in parser.attributes:
            with self.subTest(tag=tag, attrs=attrs):
                if tag == "a":
                    self.assertEqual([name for name, _ in attrs], ["href"])
                else:
                    self.assertEqual(attrs, [])

    def test_url_attribute_is_escaped_and_unsafe_scheme_has_no_link(self):
        quoted_url = 'https://example.com/job?a="quoted"&owner=tom\'s'
        quoted_card = format_job_card(_analysis(url=quoted_url))
        self.assertIn(
            'href="https://example.com/job?a=&quot;quoted&quot;&amp;owner=tom&#x27;s"',
            quoted_card,
        )

        unsafe_card = format_job_card(_analysis(url="javascript:alert(1)"))
        self.assertNotIn("<a ", unsafe_card)
        self.assertNotIn("javascript:", unsafe_card)
        self.assertIn("Посилання відсутнє", unsafe_card)

        malformed_card = format_job_card(_analysis(url="https://%zz/job"))
        self.assertNotIn("<a ", malformed_card)
        self.assertIn("Посилання відсутнє", malformed_card)


class TestGmailScanHtmlRegression(unittest.IsolatedAsyncioTestCase):
    async def test_rejected_sender_with_angle_brackets_is_escaped(self):
        settings = SimpleNamespace(
            GMAIL_ENABLED=True,
            GMAIL_USE_MOCK=False,
            GMAIL_CREDENTIALS_FILE="unused-credentials.json",
            GMAIL_TOKEN_FILE="unused-token.json",
            GMAIL_MIN_SCORE=6.0,
            TELEGRAM_CHAT_ID=123,
        )
        stats = SimpleNamespace(
            emails_fetched=1,
            duplicates_skipped=0,
            not_relevant=1,
            below_threshold=0,
            sent=0,
            errors=0,
            error_details=[],
            rejected_samples=[
                {
                    "from": "Freelancehunt <noreply@freelancehunt.com>",
                    "subject": "Project alert",
                    "reason": "not relevant",
                }
            ],
            below_score_samples=[],
            sent_analyses=[],
        )
        processor = MagicMock()
        processor.run = AsyncMock(return_value=stats)
        processor_type = MagicMock(return_value=processor)
        message = MagicMock()
        message.answer = AsyncMock()

        async def send_output(target, text, block):
            await target.answer(text)
            return True

        handler = _load_handler_function(
            "cmd_gmail_scan",
            {
                "settings": settings,
                "logger": logging.getLogger(__name__),
                "datetime": datetime,
                "escape_html": escape_html,
                "safe_http_url": safe_http_url,
                "_send_gmail_scan_output": send_output,
            },
        )

        import state

        original_history = state.gmail_scan_history[:]
        try:
            with (
                patch("gmail_agent.gmail_provider.build_provider", return_value=MagicMock()),
                patch("gmail_agent.processor.GmailJobProcessor", processor_type),
            ):
                await handler(message)
        finally:
            state.gmail_scan_history[:] = original_history

        output = "\n".join(call.args[0] for call in message.answer.await_args_list)
        self.assertNotIn("<noreply@freelancehunt.com>", output)
        self.assertIn("&lt;noreply@freelancehunt.com&gt;", output)

    async def test_all_scan_external_fields_are_escaped(self):
        settings = SimpleNamespace(
            GMAIL_ENABLED=True,
            GMAIL_USE_MOCK=False,
            GMAIL_CREDENTIALS_FILE="unused",
            GMAIL_TOKEN_FILE="unused",
            GMAIL_MIN_SCORE=6.0,
            TELEGRAM_CHAT_ID=123,
        )
        stats = SimpleNamespace(
            emails_fetched=3,
            duplicates_skipped=0,
            not_relevant=1,
            below_threshold=1,
            sent=1,
            errors=1,
            error_details=["Failure <bad> & worse"],
            rejected_samples=[{
                "from": "Name & Company <jobs@example.com>",
                "subject": "Need <b>Telegram bot</b> & CRM",
                "reason": "Budget < 5000 & deadline > 2 weeks",
            }],
            below_score_samples=[{
                "subject": "Low <score> & risk",
                "score": 5.0,
                "reason": "Value < threshold & unsafe",
            }],
            sent_analyses=[_analysis(
                title="<script>alert(1)</script>",
                budget="100 & 200",
                url='https://example.com/job?a="quoted"&b=2',
                reason="Strong <fit> & fast",
            )],
        )
        processor = MagicMock()
        processor.run = AsyncMock(return_value=stats)
        message = MagicMock()
        message.answer = AsyncMock()
        send_output, handler = _load_handler_functions(
            ["_send_gmail_scan_output", "cmd_gmail_scan"],
            {
                "settings": settings,
                "logger": logging.getLogger(__name__),
                "datetime": datetime,
                "escape_html": escape_html,
                "safe_http_url": safe_http_url,
            },
        )

        import state
        original_history = state.gmail_scan_history[:]
        try:
            with (
                patch("gmail_agent.gmail_provider.build_provider", return_value=MagicMock()),
                patch("gmail_agent.processor.GmailJobProcessor", return_value=processor),
            ):
                await handler(message)
        finally:
            state.gmail_scan_history[:] = original_history

        output = "\n".join(call.args[0] for call in message.answer.await_args_list)
        for raw in ("<jobs@example.com>", "<bad>", "<score>", "<script>", "<fit>"):
            self.assertNotIn(raw, output)
        self.assertIn("Name &amp; Company &lt;jobs@example.com&gt;", output)
        self.assertIn("Need &lt;b&gt;Telegram bot&lt;/b&gt; &amp; CRM", output)
        self.assertIn("Budget &lt; 5000 &amp; deadline &gt; 2 weeks", output)
        self.assertIn("Failure &lt;bad&gt; &amp; worse", output)
        self.assertIn("Low &lt;score&gt; &amp; risk", output)
        self.assertIn("Value &lt; threshold &amp; unsafe", output)
        self.assertIn("&lt;script&gt;alert(1)&lt;/script&gt;", output)
        self.assertIn("Budget: 100 &amp; 200", output)
        self.assertIn("Reason: Strong &lt;fit&gt; &amp; fast", output)
        self.assertIn("https://example.com/job?a=&quot;quoted&quot;&amp;b=2", output)

    async def test_rejected_block_send_failure_does_not_change_scan_result(self):
        settings = SimpleNamespace(
            GMAIL_ENABLED=True,
            GMAIL_USE_MOCK=False,
            GMAIL_CREDENTIALS_FILE="unused",
            GMAIL_TOKEN_FILE="unused",
            GMAIL_MIN_SCORE=6.0,
            TELEGRAM_CHAT_ID=123,
        )
        stats = SimpleNamespace(
            emails_fetched=1,
            duplicates_skipped=0,
            not_relevant=1,
            below_threshold=0,
            sent=0,
            errors=0,
            error_details=[],
            rejected_samples=[{"from": "safe", "subject": "safe", "reason": "safe"}],
            below_score_samples=[],
            sent_analyses=[],
        )
        processor = MagicMock()
        processor.run = AsyncMock(return_value=stats)
        message = MagicMock()
        message.answer = AsyncMock(side_effect=[None, None, RuntimeError("render send failed")])
        _, handler = _load_handler_functions(
            ["_send_gmail_scan_output", "cmd_gmail_scan"],
            {
                "settings": settings,
                "logger": logging.getLogger(__name__),
                "datetime": datetime,
                "escape_html": escape_html,
                "safe_http_url": safe_http_url,
            },
        )

        import state
        original_history = state.gmail_scan_history[:]
        state.gmail_scan_history.clear()
        try:
            with (
                patch("gmail_agent.gmail_provider.build_provider", return_value=MagicMock()),
                patch("gmail_agent.processor.GmailJobProcessor", return_value=processor),
            ):
                await handler(message)

            processor.run.assert_awaited_once()
            self.assertEqual(stats.errors, 0)
            self.assertEqual(message.answer.await_count, 3)
            self.assertEqual(state.gmail_scan_history[-1]["errors"], 0)
            self.assertEqual(state.gmail_scan_history[-1]["emails_found"], 1)
        finally:
            state.gmail_scan_history[:] = original_history


class TestGmailTestHtml(unittest.IsolatedAsyncioTestCase):
    async def test_headers_are_escaped_and_full_message_id_is_not_shown(self):
        full_id = "18f1234567890abcdef-full-gmail-id"
        diag = {
            "status": "ok",
            "message": "",
            "emails": [{
                "from": "Freelancehunt <noreply@freelancehunt.com>",
                "subject": "Need <b>bot</b> & CRM",
                "date": "Date <unsafe> & value",
                "msg_id": full_id,
                "size_kb": 1.0,
                "links": 1,
                "attachments": False,
            }],
            "sender_match_count": 1,
            "subject_match_count": 1,
            "job_alert_count": 1,
        }
        settings = SimpleNamespace(
            GMAIL_ENABLED=True,
            GMAIL_USE_MOCK=False,
            GMAIL_MIN_SCORE=6.0,
            GMAIL_CHECK_INTERVAL_MINUTES=60,
            GMAIL_CREDENTIALS_FILE="credentials<unsafe>.json",
            GMAIL_TOKEN_FILE="token&unsafe.json",
        )
        message = MagicMock()
        message.answer = AsyncMock()
        handler = _load_handler_function(
            "cmd_gmail_test",
            {"settings": settings, "_diagnose_gmail_connection": lambda *_: diag, "escape_html": escape_html},
        )

        with patch.dict(os.environ, {"GMAIL_CREDENTIALS_JSON": "set", "GMAIL_TOKEN_JSON": "set"}):
            await handler(message)

        output = "\n".join(call.args[0] for call in message.answer.await_args_list)
        self.assertIn("Freelancehunt &lt;noreply@freelancehunt.com&gt;", output)
        self.assertIn("Need &lt;b&gt;bot&lt;/b&gt; &amp; CRM", output)
        self.assertIn("Date &lt;unsafe&gt; &amp; value", output)
        self.assertIn("credentials&lt;unsafe&gt;.json", output)
        self.assertNotIn(full_id, output)

    async def test_connection_error_message_is_escaped(self):
        diag = {"status": "error", "message": "OAuth <broken> & invalid", "emails": []}
        settings = SimpleNamespace(
            GMAIL_ENABLED=True,
            GMAIL_USE_MOCK=False,
            GMAIL_MIN_SCORE=6.0,
            GMAIL_CHECK_INTERVAL_MINUTES=60,
            GMAIL_CREDENTIALS_FILE="credentials.json",
            GMAIL_TOKEN_FILE="token.json",
        )
        message = MagicMock()
        message.answer = AsyncMock()
        handler = _load_handler_function(
            "cmd_gmail_test",
            {"settings": settings, "_diagnose_gmail_connection": lambda *_: diag, "escape_html": escape_html},
        )

        with patch.dict(os.environ, {"GMAIL_CREDENTIALS_JSON": "set", "GMAIL_TOKEN_JSON": "set"}):
            await handler(message)

        output = "\n".join(call.args[0] for call in message.answer.await_args_list)
        self.assertIn("OAuth &lt;broken&gt; &amp; invalid", output)
        self.assertNotIn("<broken>", output)


class TestReplyAndSkipHtml(unittest.IsolatedAsyncioTestCase):
    async def test_reply_escapes_job_and_generated_text_and_rejects_javascript_url(self):
        job_id = "job<1>&"
        store = {job_id: {
            "title": "<script>title</script>",
            "platform": "A & B",
            "reason": "reason",
            "why_relevant": "relevant",
            "budget": "5000",
            "url": "javascript:alert(1)",
        }}
        message = MagicMock(text=f"/reply_job {job_id}")
        message.answer = AsyncMock()
        handler = _load_handler_function(
            "cmd_reply_job",
            {
                "_gmail_job_store": store,
                "logger": logging.getLogger(__name__),
                "escape_html": escape_html,
                "safe_http_url": safe_http_url,
            },
        )

        with patch("gmail_agent.reply_generator.generate_reply", AsyncMock(return_value="Draft <b>bold</b> & safe")):
            await handler(message)

        output = "\n".join(call.args[0] for call in message.answer.await_args_list)
        self.assertNotIn("<script>", output)
        self.assertNotIn("<b>bold</b>", output)
        self.assertNotIn("javascript:", output)
        self.assertIn("&lt;script&gt;title&lt;/script&gt;", output)
        self.assertIn("Draft &lt;b&gt;bold&lt;/b&gt; &amp; safe", output)

    async def test_skip_escapes_user_supplied_job_id(self):
        job_id = "missing<id>&"
        message = MagicMock(text=f"/skip_job {job_id}")
        message.answer = AsyncMock()
        handler = _load_handler_function(
            "cmd_skip_job",
            {
                "_gmail_job_store": {},
                "logger": logging.getLogger(__name__),
                "escape_html": escape_html,
            },
        )

        with patch("gmail_agent.job_store.delete_job", return_value=False):
            await handler(message)

        output = message.answer.await_args.args[0]
        self.assertIn("missing&lt;id&gt;&amp;", output)
        self.assertNotIn("missing<id>&", output)


class TestSchedulerHtml(unittest.IsolatedAsyncioTestCase):
    async def test_fatal_and_partial_error_details_are_escaped(self):
        from gmail_agent.scheduler import check_gmail_jobs

        settings = SimpleNamespace(
            GMAIL_ENABLED=True,
            GMAIL_USE_MOCK=False,
            GMAIL_CREDENTIALS_FILE="unused",
            GMAIL_TOKEN_FILE="unused",
            TELEGRAM_CHAT_ID=123,
            GMAIL_MIN_SCORE=6.0,
            admin_chat_id=456,
        )
        config_module = SimpleNamespace(settings=settings)

        fatal_bot = MagicMock()
        fatal_bot.send_message = AsyncMock()
        with (
            patch.dict(sys.modules, {"config": config_module}),
            patch("gmail_agent.gmail_provider.build_provider", side_effect=RuntimeError("fatal <tag> & error")),
        ):
            await check_gmail_jobs(fatal_bot)
        fatal_text = fatal_bot.send_message.await_args.kwargs["text"]
        self.assertIn("fatal &lt;tag&gt; &amp; error", fatal_text)
        self.assertNotIn("fatal <tag>", fatal_text)

        stats = SimpleNamespace(
            emails_fetched=1,
            duplicates_skipped=0,
            not_relevant=1,
            sent=0,
            errors=1,
            error_details=["partial <tag> & error"],
        )
        processor = MagicMock()
        processor.run = AsyncMock(return_value=stats)
        partial_bot = MagicMock()
        partial_bot.send_message = AsyncMock()
        with (
            patch.dict(sys.modules, {"config": config_module}),
            patch("gmail_agent.gmail_provider.build_provider", return_value=MagicMock()),
            patch("gmail_agent.processor.GmailJobProcessor", return_value=processor),
        ):
            await check_gmail_jobs(partial_bot)
        partial_text = partial_bot.send_message.await_args_list[0].kwargs["text"]
        self.assertIn("partial &lt;tag&gt; &amp; error", partial_text)
        self.assertNotIn("partial <tag>", partial_text)


if __name__ == "__main__":
    unittest.main(verbosity=2)
